import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Commissioner } from "next/font/google";
import Header from "./components/Header/Header";

// const inter = Inter({ subsets: ['latin'] })

const commissioner = Commissioner({
  subsets: ["cyrillic"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={commissioner.className}>
        <div className="wrapper">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
